DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS books;

CREATE TABLE genres(genre_id BIGINT generated by default as identity, genre_name VARCHAR(255));
CREATE TABLE authors(author_id BIGINT generated by default as identity, author_name VARCHAR(255));
CREATE TABLE books(book_id BIGINT generated by default as identity,  name VARCHAR(255) , author_id BIGINT, genre_id BIGINT);





